name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up elixir & erlang
        id: beam
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Install dependencies
        run: mix deps.get

      - name: Verify
        run: mix test --color --cover --raise --warnings-as-errors
